- hosts: localhost
  vars:
    username: "harsh"
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Ensure sudo is installed
      become: true
      apt:
        name: sudo
        state: present
      tags:
        - install
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install

  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/gnome-setup.yml
    - include: tasks/vlc-setup.yml
    - include: tasks/firewall-setup.yml
    - include: tasks/nala-setup.yml
    - include: tasks/git-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/bun-setup.yml

    # - include: tasks/ssh.yml
    # - include: tasks/git-setup.yml
    # - include: tasks/core-setup.yml
    # - include: tasks/node-setup.yml
    # - include: tasks/npm-packages.yml
    # - include: tasks/slack-setup.yml
    # - include: tasks/personal-projects.yml
    # - include: tasks/nvim-setup.yml
    # - include: tasks/brave.yml
    # - include: tasks/debugger.yml
    # - include: tasks/dotfiles.yml
    # - include: tasks/productivity-tools.yml
    # - include: tasks/lsp.yml
