- name: Install System Packages 1 (build-essential, git, ripgrep, g++, cmake)
  become: true
  apt:
    name: ["build-essential", "git", "ripgrep", "g++", "cmake" ,"cmake"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 ( unzip, libtool, libtool-bin, gettext, fzf, xclip, libconf, python3-gi, gir1.2-gconf)
  become: true
  apt:
    name: [ "unzip", "libtool", "libtool-bin", "gettext", "fzf", "xclip", "libgconf-2-4", "python3-gi", "gir1.2-gconf-2.0"]
  tags:
    - install
    - neovim
    - core

- name: Install Gnome Extras
  become: true
  apt:
    name: ["gnome-tweaks","gnome-shell-extensions"]
  tags:
    - install
    - neovim
    - core


