- name: Ensure .config directory exists
  file:
    path: /home/{{ username }}/.config
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  tags:
    - dot_copy
    - dotfiles
    - zsh
    - bash
    - kitty
    - nvim
    - neovim
    - lazyvim

- name: .zshrc config
  become_user: "{{ username }}"
  copy:
    src: files/.zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ username }}"
    group: "{{ username }}"
  tags:
    - dot_copy
    - dotfiles
    - zsh

- name: .bashrc config
  become_user: "{{ username }}"
  copy:
    src: files/.bashrc
    dest: "{{ ansible_env.HOME }}/.bashrc"
    owner: "{{ username }}"
    group: "{{ username }}"
  tags:
    - dotfiles
    - bash
    - dot_copy

- name: Nvim config files
  become_user: "{{username}}"
  copy:
    src: files/.config/nvim/
    dest: $HOME/.config/nvim
    owner: "{{username}}"
    group: "{{username}}"
  tags:
    - dotfiles
    - nvim
    - neovim
    - lazyvim
    - dot_copy

- name: Kitty config files
  become_user: "{{username}}"
  copy:
    src: files/.config/kitty/
    dest: $HOME/.config/kitty
    owner: "{{username}}"
    group: "{{username}}"
  tags:
    - dotfiles
    - kitty
    - dot_copy

- name: starship.toml config
  become_user: "{{username}}"
  copy:
    src: files/.config/starship.toml
    dest: $HOME/.config/starship.toml
    owner: "{{username}}"
    group: "{{username}}"
  tags:
    - dotfiles
    - starship
    - zsh
    - dot_copy
