- name: Install Gnome Extras
  become: true
  apt:
    name: ["gnome-tweaks", "gnome-shell-extensions"]
  tags: &tags_for_gnome_tasks ["install", "productivity", "gnome"]

- name: Dock icon click to toggle app
  shell: gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
  tags: *tags_for_gnome_tasks

