- name: Install nvm
  become_user: "{{ username }}"
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  environment:
    NVM_DIR: "{{ nvm_dir }}"
  tags: &tags_for_nvm_tasks ["install", "productivity", "nvm", "node"]

- name: Install NODE=20.14.0
  become_user: "{{ username }}"
  shell: |
    . {{ nvm_dir }}/nvm.sh && \
    nvm install 20.14.0
  environment:
    NVM_DIR: "{{ nvm_dir }}"
  tags: *tags_for_nvm_tasks
  
