- name: Install teams-for-linux
  become: true
  command: snap install teams-for-linux
  tags: &tags_for_teams_tasks ["install", "teams"]

- name: Ensure autostart directory exists
  file:
    path: /home/{{ username }}/.config/autostart
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: *tags_for_teams_tasks

- name: Adding teams-for-linux auto start
  become_user: "{{username}}"
  copy:
    src: files/teams-for-linux.desktop
    dest: ${HOME}/.config/autostart/teams-for-linux.desktop
    owner: "{{username}}"
    group: "{{username}}"
    mode: "0755"
  tags: *tags_for_teams_tasks
